tailwind.config = {
  darkMode: "class", // enable dark mode via class ".dark"
  theme: {
    // breakpoints, colors, shadows, fontFamily
    extend: {
      screens: {
        xs: "450px",
        sm: "575px",
        md: "768px",
        lg: "992px",
        xl: "1200px",
        "2xl": "1400px",
      },
      colors: {
        background: "var(--background)",
        "background-95": "var(--background-95)",
        "background-60": "var(--background-60)",
        foreground: "var(--foreground)",
        "foreground-o80": "var(--foreground-o80)",
        "foreground-o60": "var(--foreground-o60)",
        primary: "var(--primary)",
        "primary-o90": "var(--primary-o90)",
        "primary-o5": "var(--primary-o5)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-o80": "var(--muted-o80)",
        "muted-o50": "var(--muted-o50)",
        "muted-o30": "var(--muted-o30)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-o80": "var(--accent-o80)",
        "accent-foreground": "var(--accent-foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
          950: "var(--color-gray-950)",
          dark: "var(--color-gray-dark)",
          light: "var(--color-gray-light)",
        },
      },
      boxShadow: {
        "sign-up": "var(--shadow-sign-up)",
        one: "var(--shadow-one)",
        two: "var(--shadow-two)",
        three: "var(--shadow-three)",
        sticky: "var(--shadow-sticky)",
        "sticky-dark": "var(--shadow-sticky-dark)",
        "feature-2": "var(--shadow-feature-2)",
        submit: "var(--shadow-submit)",
        "submit-dark": "var(--shadow-submit-dark)",
        btn: "var(--shadow-btn)",
        "btn-hover": "var(--shadow-btn-hover)",
        "btn-light": "var(--shadow-btn-light)",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
    },
  },
};
